const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ars=new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0});
// Generated by scripts/build-marketing-reference.cjs. Do not edit.
function courseClassSchedule(code, fallback) {
        const match = String(code || "").match(/^\d{4}-\d{2}-\d{2}-[A-Z]{2}-(\d{1,2}:\d{2})-(\d{1,2}:\d{2})-/i);
        if (match) {
          const toMinutes = (time) => {
            const [hours, minutes] = time.split(":").map(Number);
            return hours * 60 + minutes;
          };
          let duration = toMinutes(match[2]) - toMinutes(match[1]);
          if (duration < 0) duration += 24 * 60;
          const hours = Math.floor(duration / 60), minutes = duration % 60;
          const durationLabel = [hours ? hours + " h" : "", minutes ? minutes + " min" : ""].filter(Boolean).join(" ");
          return `${match[1]} a ${match[2]}${durationLabel ? " · " + durationLabel : ""}`;
        }
        const value = String(fallback || "").trim();
        return value && !/(1899|GMT|Standard Time)/i.test(value) ? value : "Horario a confirmar";
      }
      function coursePaymentPromotions(course) {
        const monthlyFee = Number(course.monthlyFee) || 0;
        const fullPrice = Number(course.fullPrice) || 0;
        const duration = String(course.duration || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
        const monthMatch = duration.match(/(\d+(?:[.,]\d+)?)\s*(?:mes|meses)\b/);
        const months = monthMatch ? Number(monthMatch[1].replace(",", ".")) : 0;
        const basePrice = monthlyFee > 0 && months > 0 ? monthlyFee * months : fullPrice;
        if (!(basePrice > 0)) {
          return '<div class="course-promotion-missing">Promociones: falta informar la duración en meses o el valor total del curso para calcular los importes.</div>';
        }
        const registration = 26000;
        const cardTotal = basePrice + registration;
        const cashTotal = basePrice * 0.8;
        const transferTotal = basePrice * 0.8 + registration * 0.5;
        const calculation = monthlyFee > 0 && months > 0
          ? `${months} ${months === 1 ? "mes" : "meses"} × ${ars.format(monthlyFee)} = ${ars.format(basePrice)}`
          : `Valor total del curso: ${ars.format(basePrice)}`;
        return `<section class="course-promotions"><div class="course-promotions-title"><strong>Promociones por pago del curso completo</strong><small>Precio base: ${esc(calculation)}</small></div><div class="course-promo-list"><div class="course-promo"><div class="course-promo-name">Tarjeta de crédito</div><div class="course-promo-detail">Curso + inscripción de ${ars.format(registration)} · hasta 6 cuotas sin interés de ${ars.format(cardTotal / 6)}</div><div class="course-promo-total">${ars.format(cardTotal)}</div></div><div class="course-promo"><div class="course-promo-name">Efectivo</div><div class="course-promo-detail">20% de descuento · inscripción bonificada</div><div class="course-promo-total">${ars.format(cashTotal)}</div></div><div class="course-promo"><div class="course-promo-name">Transferencia</div><div class="course-promo-detail">20% de descuento + 50% de inscripción (${ars.format(registration / 2)})</div><div class="course-promo-total">${ars.format(transferTotal)}</div></div></div></section>`;
      }

const HOLIDAYS=new Set(['2026-01-01','2026-02-16','2026-02-17','2026-03-23','2026-03-24','2026-04-02','2026-04-03','2026-05-01','2026-05-25','2026-06-15','2026-06-20','2026-07-09','2026-07-10','2026-08-17','2026-10-12','2026-11-23','2026-12-07','2026-12-08','2026-12-25']);
const workProjection=(month,sales,override)=>{const [y,m]=month.split('-').map(Number),now=new Date(),last=new Date(y,m,0),current=now.getFullYear()===y&&now.getMonth()+1===m;let total=0,elapsed=0;for(let d=1;d<=last.getDate();d++){const date=new Date(y,m-1,d),key=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;if(date.getDay()!==0&&!HOLIDAYS.has(key)){total++;if(!current||date<=now)elapsed++}}const effective=Number(override)||total;return current&&elapsed?Math.round(sales/elapsed*effective):sales};

function coursePricing(course) {
        const monthlyFee = Number(course.monthlyFee) || 0;
        const fullPrice = Number(course.fullPrice) || 0;
        const duration = String(course.duration || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
        const monthMatch = duration.match(/(\d+(?:[.,]\d+)?)\s*(?:mes|meses)\b/);
        const months = monthMatch ? Number(monthMatch[1].replace(",", ".")) : 0;
        const basePrice = monthlyFee > 0 && months > 0 ? monthlyFee * months : fullPrice;
        if (!(basePrice > 0)) {
          return null;
        }
        const registration = 26000;
        const cardTotal = basePrice + registration;
        const cashTotal = basePrice * 0.8;
        const transferTotal = basePrice * 0.8 + registration * 0.5;
        const calculation = monthlyFee > 0 && months > 0
          ? `${months} ${months === 1 ? "mes" : "meses"} × ${ars.format(monthlyFee)} = ${ars.format(basePrice)}`
          : `Valor total del curso: ${ars.format(basePrice)}`;
        return { monthlyFee, months, basePrice, registration, cardTotal, cashTotal, transferTotal };
}
export { courseClassSchedule, coursePaymentPromotions, coursePricing, workProjection };
